require('dotenv').config({path: __dirname + '/.env'})
const {GoogleSpreadsheet} = require('google-spreadsheet');

async function accessSpreadsheet() {

  // Initialize the sheet
  const doc = new GoogleSpreadsheet(process.env.SPREADSHEET_ID);

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.GOOGLE_PRIVATE_KEY,
  });

  await doc.loadInfo(); // loads document properties and worksheets
  console.log(`The title of the spreadsheet is: ${doc.title}`);
}
accessSpreadsheet();